---
# most of these variables should be passed in to ansible with --extra-vars "@your_file.json"
wiki:
  install_path: /var/www/html/mediawiki
  user: apache
  group: apache
  site_name: MediaWiki
  meta_namespace: MediaWiki
  base_url: http://www.example.com
  domain: example
  logo:
    path: images/logo.jpg
    source_file: none
    copy_custom_file: false
  emergency_contact: apache@example.com
  password_sender: apache@example.com
  secret_key: a009c3037fa5af6534ca1bb4cb2f801610d5055edad74f08841fd0fb87929a69
  upgrade_key: ae59daef86893163
  cache:
    type: CACHE_NONE
    mem_cached_servers: array()
  db:
    type: mysql
    server: mysql.example.com
    name: mediawiki
    user: mediawiki
    password: mediawiki
    prefix: ""
    table_options: "ENGINE=InnoDB, DEFAULT CHARSET=binary"
  skins:
    - CologneBlue/CologneBlue.php
    - Modern/Modern.php
    - MonoBook/MonoBook.php
    - Vector/Vector.php
  default_skin: vector
  permissions:
    groups:
      - { group: "*", permission: "createaccount", allowed: "false" }
  extensions:
    - Cite/Cite.php
    - Gadgets/Gadgets.php
    - InputBox/InputBox.php
    - Nuke/Nuke.php
    - ParserFunctions/ParserFunctions.php
    - Poem/Poem.php
    - Renameuser/Renameuser.php
    - SpamBlacklist/SpamBlacklist.php
  custom_lines:
    - "# speed improvements"
    - $wgUseGzip = true;
